version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install pandas scikit-learn joblib boto3 sagemaker
      - echo "Installation complete."

  pre_build:
    commands:
      - echo "Environment check..."
      - python --version
      - pip list | grep -E "(pandas|scikit|boto3|sagemaker)"
      - echo "Current directory structure:"
      - find . -type f -name "*.py" -o -name "*.csv" | head -20
      - echo "Checking for csv_folder..."
      - ls -la csv_folder/ 2>/dev/null || echo "csv_folder not found or empty"

  build:
    commands:
      - echo "Running partial_fit automation..."
      - python partial_fit_automate.py || { echo "Script failed with exit code $?"; exit 1; }
      - echo "Script completed successfully."

  post_build:
    commands:
      - echo "Build completed at $(date)"
      - echo "Check CloudWatch logs for deployment status"

artifacts:
  files:
    - '**/*'
