version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Updating pip and installing dependencies..."
      - pip install numpy pandas scikit-learn joblib boto3 sagemaker
      - echo "Installation complete."

  build:
    commands:
      - echo "Listing source files..."
      - ls -R $CODEBUILD_SRC_DIR

      - echo "Running partial_fit automation..."
      - python partial_fit_automate.py

artifacts:
  files:
    - '**/*'
