version: 0.2

env:
  variables:
    SAGEMAKER_VERSION: "2.254.1"

phases:
  install:
    runtime-versions:
      python: 3.11  # or 3.10 to match notebook
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install pandas scikit-learn joblib boto3
      - pip install sagemaker==2.254.1  # Match notebook version
      - echo "Installation complete."
      
      # Verify installation
      - echo "Verifying sagemaker version..."
      - python -c "import sagemaker; print(f'SageMaker version: {sagemaker.__version__}')"
      - python -c "from sagemaker import Model; print('✓ Model class imported successfully')"

  pre_build:
    commands:
      - echo "Environment check..."
      - python --version
      - pip list | grep -E "(sagemaker|boto3)"
      - echo "Checking for csv_folder..."
      - ls -la csv_folder/ 2>/dev/null || echo "csv_folder not found or empty"

  build:
    commands:
      - echo "Running partial_fit automation..."
      - python partial_fit_automate.py || { echo "Script failed with exit code $?"; exit 1; }

  post_build:
    commands:
      - echo "Build completed at $(date)"
      - echo "Check CloudWatch logs for deployment status"

artifacts:
  files:
    - '**/*'
