version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install pandas scikit-learn==1.7.2 joblib boto3 sagemaker==2.254.1
      - echo "Installation complete."

  pre_build:
    commands:
      - echo "Environment check..."
      - python --version
      - pip list | grep -E "(sagemaker|boto3|pandas|scikit)"
      - echo "Checking for csv_folder..."
      - ls -la csv_folder/ 2>/dev/null || echo "csv_folder not found or empty"

  build:
    commands:
      - echo "Running partial_fit automation..."
      - python partial_fit_automate.py || { echo "Script failed with exit code $?"; exit 1; }

  post_build:
    commands:
      - echo "Build completed at $(date)"
      - echo "Check CloudWatch logs for deployment status"

artifacts:
  files:
    - '**/*'
