version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Updating pip and installing dependencies..."
      - pip install numpy==1.26.4 pandas==1.5.3 scikit-learn==1.2.2 joblib boto3
      - echo "Installation complete."

  build:
    commands:
      - echo "Listing source files..."
      - ls -R $CODEBUILD_SRC_DIR

      - echo "Running partial_fit automation..."
      - python partial_fit_automate.py

artifacts:
  files:
    - '**/*'
